apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ivy-testing

resources:
  - ../../base
  - sealed-settings.yaml

images:
  - name: registry.cn-shanghai.aliyuncs.com/ivysci/gpt-researcher
    newTag: e3a2fd4ac5dd352188c24b8d9168e674cb056c9b
